//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tma.bit.local/")]
public interface IService1Soap {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/HelloWorld", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    string HelloWorld();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getTrainerTable", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getTrainerTable();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getTrainerFromNavision", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getTrainerFromNavision();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getZeitdatenPerMAString", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getZeitdatenPerMAString(string[] persids);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getZeitdaten", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getZeitdaten();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/ZeitschemaMitWochentagen", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet ZeitschemaMitWochentagen();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/Stempeldaten", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet Stempeldaten(string[] persids, System.DateTime von, System.DateTime bis);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/StempeldatenPerZeitraum", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet StempeldatenPerZeitraum(System.DateTime von, System.DateTime bis);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/Planzeiten", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet Planzeiten();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/PlanzeitenPerPersId", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet PlanzeitenPerPersId(string[] Persids);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/PlanzeitenPerPersIdUndZeitraum", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet PlanzeitenPerPersIdUndZeitraum(string[] PersIds, System.DateTime von, System.DateTime bis);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/Verrechnungszeiten", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet Verrechnungszeiten();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/VerrechnungszeitenPerPersIds", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet VerrechnungszeitenPerPersIds(string[] PersIds);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/VerrechnungszeitenPerPersidsUndZeitraum", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet VerrechnungszeitenPerPersidsUndZeitraum(string[] persIds, System.DateTime von, System.DateTime bis);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/Feiertage", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet Feiertage();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getSollZeiten", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getSollZeiten();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getSollZeitenPerPersIDAndDatum", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getSollZeitenPerPersIDAndDatum(string[] persid, System.DateTime von, System.DateTime bis);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getSollZeitenFeiertage", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getSollZeitenFeiertage();
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getSollZeitenFeiertagePerPersIDAndDatum", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getSollZeitenFeiertagePerPersIDAndDatum(string[] persid, System.DateTime von, System.DateTime bis);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tma.bit.local/getUrlaubssaldo", RequestNamespace="http://tma.bit.local/", ResponseNamespace="http://tma.bit.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    System.Data.DataSet getUrlaubssaldo();
}
